### PR TITLE
Automatic deletion of old signatures

### PR DESCRIPTION
**Pull request by nyrocron**
when adding a system, automatically delete wormholes older than 48h and other sigs older than 14d

was not entirely sure how to add settings, let me know if anything else is needed.

### CODE REVIEW

**Comment by nyrocron** [comment]
don't merge yet - doing some more testing

**Comment by nyrocron** [comment]
closing temporarily while i do some more testing, will probably be done tomorrow

**Comment by nyrocron** [comment]
fixed one small bug, otherwise tests with various sig ages looked fine.
configurable currently only via admin map settings because adding it to user settings is quite a bit more effort.

**Comment by marbindrakon** [comment]
This has been merged to the SSC mapper for live testing. It will go into develop in a few days if nothing blows up.

**Pull request merged**
