### PR TITLE
Added B520 wormhole, fixed B041 and C248 jump/max mass

### PR DESCRIPTION
**Pull request by Zumochi**
Not sure if this requires a migration?

Let me know!

### CODE REVIEW

**Comment by marbindrakon** [comment]
The B041 and C248 changes will require data migrations to update existing instances.

**Comment by Zumochi** [comment]
Is there a template for this or should I grab one of the existing ones? I have no experience with migrations :D

**Comment by Zumochi** [comment]
Let me know if I did anything wrong! Tested in my own instance without issues.

**Comment by marbindrakon** [comment]
Thanks!

**Pull request merged**
