### PR TITLE
RESTful WSpace

### PR DESCRIPTION
**Pull request by illuser**
## TODO :shipit:

* Integrate compilation of app.js based on installed modules/plugins.
* Clean up app.js compilation.
* Write unit testing (_Lykouleon, you are a mongo_. :jiggled:).
* Generate index.jade > index.html for django.
* Make a git hook to install/generate frontend.
* gulp-watch for development and/or dynamic module/plugin loading.
* Proper jsdoc docblocks.
* Add docs to eve-wspace docs.
* Generate navigation with django or via API

## Modules
* Core :fire:
  * API :question:
  * Search :question:
* Jabber
  * Alerts
  * Slack :question:
* Map :fire:
* POS
* SiteTracker :fire:
* Account :fire:
* _Recruitment_

## Changes
* Static 'images' changed to 'img'
* Bootstrap and other vendor stylesheets combined into single vendors.css
* Vendor javascript combined into single vendors.js
* Application javascript combined into app.js
* Application stylesheets combined into single app.css
* Application stylesheets moving to BEM methodology.

## Development

Requirements

* nodejs > 0.12.0 < 0.13.0 | iojs > 2.0.0 < 3.0.0
* python > 2.7 < 3.0.0
* gcc ~5.2.0

Recommended
* [nvm](https://github.com/creationix/nvm) ~ 0.25.4
* [pyenv](https://github.com/yyuu/pyenv) ~ v20150719

```bash
# Clone the main eve-wspace repo
git clone https://github.com/eve-wspace/eve-wspace

# Checkout the rest-api branch
git checkout rest-api

# Set up eve-wspace

# Change to the frontend folder
cd eve-wspace/evewspace/frontend

# Install npm dependencies
npm i

# Begin breaking things

# Build the frontend
gulp build

# Collect the static assets with django
../manage.py collectstatic
```

### CODE REVIEW

**Comment by nyrocron** [comment]
don't like the node.js requirement.

**Comment by Zumochi** [comment]
Looks like you did some work :grin:

But I have to agree with nyrocron. This is a django application after all. Why would it need node?

**Comment by illuser** [comment]
Node is for gulpjs/browserify/node-sass etc etc etc. All of the backend stays in python, only the frontend is in javascript.

Depending on how marbin wants to move forward with plugins, rebuilding the frontend becomes a major chore without some form of frontend build process.

**Comment by nyrocron** [comment]
Yes but it should be done in python.

**Comment by marbindrakon** [comment]
Merging this into the rest branch for now. I'm comfortable with some js stuff as build-time requirements. We will have to get a proper build process in place before this makes it to develop.

**Pull request merged**
