### PR TITLE
Django 1.8

### PR DESCRIPTION
**Pull request by Maarten28**
Made EWS workable under Django 1.8 with a clean install. Requirements and db shell file have been updated to create a working VM through the vagrantfile. 

Currently no testing has occured on existing installs and how to upgrade (current suggestion is to back up the db and start from a clean install), some bugs might still be present, but it is a start. Most obvious functionalities have been tested. Stuff which requires external connections (Slack/jabber) have not been tested.

All deprecated features which are unusable from Django 1.9 forward have not been changed/updated. There are some warnings wrt the database, but since I did not want to touch the DB before the new migration files were created these were not resolved;

### CODE REVIEW

**Comment by Maarten28** [comment]
The following issues have been addressed in this PR: 

https://github.com/evewspace/eve-wspace/issues/153
https://github.com/evewspace/eve-wspace/issues/106

**Comment by Maarten28** [comment]
The following functionality has been lost in the UI rework: 
- The slider to zoom in or out (didn't find a workable plugin yet for Bootstrap 3.1)
- Combining tabs (too much effort to maintain)

**Comment by Maarten28** [comment]
The following is a draft upgrade guide from Django 1.6 EVE-Wspace install (2015.12 release) to the code on this PR/the fork's branch Django 1.8 (now 2015.2 release). For now it is only meant to be used on a dev environment to confirm that the steps below are ok. 

The following has to be executed in a virtual env or with sudo:

Some ubuntu version won't uninstall south properly w/o the last version of pip:
`pip install --upgrade pip`

Install django 1.8:
`pip install --upgrade django==1.8.7`

Check version: 
`pip show Django`

Delete south:
`pip uninstall South`

Check whether south is uninstalled (should show nothing):
`pip show South`

Go to the location where the application/manage.py is located.

Put in the new version of EVE W-space by your prefered method (Git, replace the files etc.). 

Start the server to confirm no server errors are present except for not having applied the migrations. Warnings about tables (as can be seen above) are ok. 

Shut the server down again. 

Confirm that all migrations are present by creating any remaining ones:
`./manage.py makemigrations`

Perform the following migrations: 
`./manage.py migrate auth 0001 --fake-initial`

You will get asked to delete stale content types (Map | activepilot, account | playtime and account | userprofile), select yes.

```
./manage.py migrate auth
./manage.py migrate API 0001 --fake-initial
./manage.py migrate Alerts 0001 --fake-initial
./manage.py migrate Jabber 0001 --fake-initial
./manage.py migrate Map 0001 --fake-initial
./manage.py migrate POS 0001 --fake-initial
./manage.py migrate SiteTracker 0001 --fake-initial
./manage.py migrate Slack 0001 --fake-initial
./manage.py migrate account 0001 --fake-initial
./manage.py migrate core 0001 --fake-initial
./manage.py migrate sessions 0001 --fake-initial
./manage.py migrate sites 0001 --fake-initial
./manage.py migrate API 0002 --fake
./manage.py migrate Alerts 0002 --fake
./manage.py migrate Jabber 0002 --fake
./manage.py migrate Map 0002 --fake
./manage.py migrate POS 0002 --fake
./manage.py migrate SiteTracker 0002 --fake
```

In case you run the Recruitment tools, run the following fake migrations as well:
`./manage.py migrate Recruitment 0001 --fake-initial`
`./manage.py migrate Recruitment 0002 --fake`

To finish off with any (other) new migrations: 
`./manage.py migrate`

Unfortunately one migration of auth is not being applied correctly, therefore a manual query is nescessary (login to your SQL server and select the right DB):
`ALTER TABLE account_ewsuser MODIFY last_login datetime NULL;`

**Comment by Zumochi** [comment]
The docs need updating for the new installation process.

**Pull request merged**
