### PR TITLE
Minor UI improvements

### PR DESCRIPTION
**Pull request by proycon**
- Friendly name is reported immediately after system name (in parentheses) and consistently so across all panes, not just system details.
- Pencil icon to edit system details is added to all panes, for quick access
- Signature purge/confirm button took up too much vertical space, is now a floaty button on the right
- Add sig button didn't fit on row, relabeled to just "add"
- Minor transparency on modal dialogs and system tooltips
- Main nav bar takes less height (it took away from the map real estate whilst not being used much)
- Modal dialogs take less space now (point 2 of issue #239)
- Set destination buttons in destination list are smaller now
- k-space details are reported on one line instead of an ugly table, sec status coloured

### CODE REVIEW

**Comment by raphendyr** [comment]
Nice changes, though it would be cool if the commit list would be bit shorter, e.g. commit "typo" could be squashed. Also those "3rd, attempt".

**Comment by proycon** [comment]
Yeah, I'm a bit of a commit-early, commit-often type, which tends to lead to this :) I tried to squash some but that kind of messed things up, I'd rather not mess with history...

**Comment by raphendyr** [comment]
Sure. I recommend learning to use rebase efectively at some point though. It's so much easier to find bugs from projects.

Anycase, better to commit often and early, instead of losing data.

edit: oh and "commit --amend" is handy for small changes, if you don't use git hooks to push to production.

**Comment by proycon** [comment]
Ok, I squashed a whole bunch of commits now (see above) ...should be better I hope.. assuming nobody pulled this in before now (if so, reset and do again).

**Comment by raphendyr** [comment]
Cool. Looks way better imho :)
Give it 1-2 years and rebase and history cleaning is just normal task :P

**Comment by raphendyr** [comment]
Btw. Not exatly for this, but could there be `addWaypoint` button next to `setDestination`? info system info and saved locations?

**Comment by proycon** [comment]
There used to be such a button in the destination list if I recall, I may even have been the one who removed it at some point (not in this PR) cause I didn't see the need for it and found it cluttering and confusing :$

**Comment by raphendyr** [comment]
Well.. I personally check route distances between 2 random entry systems (e.g. 2 maps) setting the first as destination and second as waypoint. The game calculates "N+" number as jumps and the real distance is "N-1". So to find best hisec entry to travel to some other map (e.g. operation) I use that system. Thus the add waypoint would be really handy. Though I think that button can be way smaller than the set destination.

**Comment by proycon** [comment]
Actually, I implemented a feature for that in my `feat_mapoverlap` branch (https://github.com/proycon/eve-wspace/tree/feat_mapoverlap). It shows distance between all k-space exits/entries on all maps (and mentions on which map it is). It's not in this PR as it's a bit unpolished still because it doesn't take any map permissions into account.

**Comment by raphendyr** [comment]
Omg. that would be handy! I hope you get it polished some day.

Still I'm pretty sure that add waypoint might be usefull sometimes. As it's not so ofthen the button could be small or otherwise less space taking. Even if we can get that as context menu for set destination button, that could work.

Or actually the system name. Right click (or left if that is ok) the system name and it would show context menu with actions "show info", "set destination" and "add waypoint".

**Comment by Zumochi** [comment]
:+1: better than attempting to double click on something ten times before it works.

**Comment by raphendyr** [comment]
Can you rebase this on top of current develop and squash some of the commits at least.  Most are just small style changes so I don't see need for them to be separate commits.

**Comment by proycon** [comment]
Right, I'll try to get onto this in the coming days.

**Comment by proycon** [comment]
Sorry for the delay, I just rebased my `minoruiimprovements` branch on the `develop` branch. I'm a bit confused about all of the older unsquashed commits being part of this PR though, things seem a bit messy... Probably even more messy than before the rebase :/

**Comment by proycon** [comment]
I undid my rebase again, will try anew

**Comment by proycon** [comment]
Rebase complete, conflict resolved.

**Comment by raphendyr** [comment]
I'll test this and merge if fine. Thanks in advance.

**Comment by raphendyr** [comment]
Also, if you like you can clean up the history and squash some commits if there is no need them to be separate. E.g. commit "Fix regression" could be merged into the commit that created regression.

**Comment by Maarten28** [comment]
Tested, looks good except two minor UI issues which I'll put in a new issue. Gonna merge it.

**Pull request merged**
