### PR TITLE
Set statics for J005923

### PR DESCRIPTION
**Pull request by raphendyr**
statics are U210 and K346 based on http://www.ellatha.com/eve/WormholeSystemview.asp?key=005923

### CODE REVIEW

**Comment by raphendyr** [comment]
Apparently this information was ingame validated by our corpmembers too. I presume there were closing extra holes.

**Comment by Maarten28** [comment]
We're missing all statics from Shattered & Drifter WHs . They were never added because C2 & C4s now have 3 statics if they are shattered and afaik the system is not build to handle them.

**Comment by Zumochi** [comment]
Wait shattered systems actually have statics?

**Comment by Maarten28** [comment]
Yes, it is the normal amount of statics of a similar class WH + 1 k-space. The k-space in C5/C6 however is not cap capable (for example I know for C5>LS a U210 is used).

**Comment by raphendyr** [comment]
Any ideas how to fix that static hole thing?

**Comment by AceMgy** [comment]
Wouldn't simply adding a third static that defaults to null here:
https://github.com/evewspace/eve-wspace/blob/459cfefb5f1b0e05b4bbec9e1fb270f1c5e259c3/evewspace/Map/models.py#L221-L228

Fix this?  Or is there something else that doesn't play nicely with that?

**Comment by Maarten28** [comment]
Partially, also need to make/apply the migrations and add them to the templates/UI. It is not hard, it just needs to be done sometime. From that point forward all statics for shattered WHs need to be updated.

**Comment by AceMgy** [comment]
I'll look into it.  Little fuzzy on custom migrations as I've only done the django tutorial but I'm hungry for something to do.

**Comment by AceMgy** [comment]
This has partially been fixed in my pull request #229 

I say partially because I didn't change any of the shattered systems statics, only added the functionality for systems with three statics.  Looks like I'll have to modify those eventually.

Is this spreadsheet:
https://docs.google.com/spreadsheets/d/1wbMdouiafkE-yT7Du0eKF0aoeF9gjNQco4ms74VX1dw/edit#gid=0
all eve knows about shattered statics?  Because it's woefully incomplete.

Also just realized the .json file in fixtures only uses pk id.  Ohh boy...

**Comment by Zumochi** [comment]
It is the best documented I believe. Of course much more is  known but I doubt many people use/update it.

**Comment by raphendyr** [comment]
Here is tool to convert that google sheet to db queries. Just download sheet as csv and run the script in environment with eve w-space mysql/mariadb: 
https://gist.github.com/raphendyr/a3e9589cafff56522f31

**Comment by raphendyr** [comment]
From developing the script I noticed that eve-wspace is missing wormhole types D485 and X574 at least.

**Comment by Zumochi** [comment]
Interesting, neither of those are on [Ellatha's list](http://www.ellatha.com/eve/wormholelist.asp).

What wormhole types are they? Don't recall coming across the X574 at least.

**Comment by raphendyr** [comment]
Well. There were in that linked google docs. I have no more info :(

**Comment by AceMgy** [comment]
I guess we could add them with 0 max and 0 jump mass to make it clear they're unknown atm.

Feels super icky but I don't like missing wormhole types.

**Comment by raphendyr** [comment]
@AceMgy  That script has commented out the line that edits the db. django had some script to dump the fixtures, so I though this would be easier way.

Also, we need to check if those wormhole types are just typos or some other errors. It might be there really do not even exists.

**Comment by Zumochi** [comment]
Not all shattered systems have 3 statics, I think it's only a few.

**Comment by raphendyr** [comment]
To my knowledge (based on the first reply) only the C2 and C4 class shattered systems.

**Comment by Zumochi** [comment]
This pull request requires a migration. Besides this, I think it would be nice to get one big PR for all the currently known shattered statics.

**Comment by raphendyr** [comment]
I presume this is waiting the big PR and is closed then. Good place to track the issue.

**Pull request closed without merging**
